ALTER TABLE boards ADD COLUMN createdAt DATETIME;
ALTER TABLE boards ADD COLUMN updatedAt DATETIME;

ALTER TABLE notes ADD COLUMN createdAt DATETIME;
ALTER TABLE notes ADD COLUMN updatedAt DATETIME;

UPDATE boards SET createdAt = CURRENT_TIMESTAMP WHERE createdAt IS NULL;
UPDATE boards SET updatedAt = CURRENT_TIMESTAMP WHERE updatedAt IS NULL;

UPDATE notes SET createdAt = CURRENT_TIMESTAMP WHERE createdAt IS NULL;
UPDATE notes SET updatedAt = CURRENT_TIMESTAMP WHERE updatedAt IS NULL;
