CREATE TRIGGER IF NOT EXISTS update_boards_updatedAt
    AFTER UPDATE ON boards
    FOR EACH ROW
BEGIN
    UPDATE boards SET updatedAt = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;

CREATE TRIGGER IF NOT EXISTS update_notes_updatedAt
    AFTER UPDATE ON notes
    FOR EACH ROW
BEGIN
    UPDATE notes SET updatedAt = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
